BankProject/Controllers/TransactionDetailController.cs
using BankProj.BankApplication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BankProj.Controllers
{
    public class TransactionDetailController : Controller
    {
        private readonly AssignmentDBContext _context;
       
        public TransactionDetailController(AssignmentDBContext context)
        {
            _context = context;
        }
        public IActionResult Transdetail(int credit,string name,int debit,string toname)
        {
            long? balance, transamt;
            string madeby, madeto, transtype, date, status;
            UserAccountDetail us = new UserAccountDetail();
            BankInformation b = new BankInformation();
            us= _context.UserAccountDetails.FirstOrDefault(m =>m.FullName==name);
            b=_context.BankInformations.FirstOrDefault(n => n.AccountNumber == us.AccountNumber);
            DateTime dt = DateTime.UtcNow;
            if(credit>0)
            {
                balance = b.Balance + credit;
                b.Balance = balance;
                madeto = "****";
                transamt = credit;
                transtype = "Credit";
            }
            else if(debit>0)
            {
                balance = b.Balance - debit;
                b.Balance = balance;
                madeto = toname;
                transamt = debit;
                transtype = "Debit";
            }
            else
            {
                return NotFound();
            }
            madeby = name;
            date = dt.ToShortDateString();
            status = "Success";
            TransactionDetail _transdetail = new(madeby, madeto, transamt, transtype, date, status, balance);
            _context.TransactionDetails.Add(_transdetail);
            _context.SaveChanges();
            _context.BankInformations.Update(b).Property(x => x.BankInfoId).IsModified = false; 
            _context.SaveChanges();
            return RedirectToAction("Def","Home");
        }
        public IActionResult passbook()
        {
            string gmail = HttpContext.User.Identity.Name;
            UserAccountDetail us = new UserAccountDetail();
            TransactionDetail b = new TransactionDetail();
            us = _context.UserAccountDetails.FirstOrDefault(m => m.Email == gmail);
            b = _context.TransactionDetails.FirstOrDefault(n => n.MadeBy == us.FullName);
            ViewBag.name = b.MadeBy;
            return View(_context.TransactionDetails.ToList());
        }
        public IActionResult Index()
        {
            TransactionDetail b = new TransactionDetail();
            return View(b);
            
        }
        [HttpPost]
        public IActionResult Index(int id)
        {
            TransactionDetail b = new TransactionDetail();
            b = _context.TransactionDetails.Find(id);
            return View(b);
        }
       
    }
}

BankProject/Views/TransactionDetail/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model BankProj.BankApplication.TransactionDetail

<form asp-controller="TransactionDetail" asp-action="Index" class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" name="id" aria-label="Search">
    <button id="myselection" class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>
@if (Model.MadeBy == null)
{
    <h4 class="text-md-center">Kindly enter a valid Transaction ID</h4>
}
else if (Model.TransactionId == 0)
{
    <h4 class="text-md-center">Result Not Found</h4>

}
else
{
    <div class="myDiv">
        <h1>@Model.TransactionId,@Model.Date,@Model.MadeBy,@Model.MadeTo,@Model.TransactionAmount</h1>
    </div>
}

BankProject/Views/TransactionDetail/passbook.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<BankProj.BankApplication.TransactionDetail>
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#myselection').on('change', function () {
                var demovalue = $(this).val();
                $("div.myDiv").hide();
                $("#show" + demovalue).show();
            });
        });
    </script>
</head>
<div class="form-group row">
    <label for="inputselect" class="col-sm-3 col-form-label">Type of Transaction</label>
    <div class="col-sm-3">
        <select id="myselection">
            <option>Select Option</option>
            <option value="Credit">Credit</option>
            <option value="Debit">Debit</option>
        </select>
    </div>
</div>
<div id="showCredit" class="myDiv" style="display:none">
    <div class="col-md-12">
        <table class="table table-sm">
            <thead class="thead-dark">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.TransactionId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.MadeBy)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TransactionAmount)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TransactionType)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Date)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Status)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Balance)
                    </th>
                </tr>
            </thead>
            <tbody class="bg-light">
                @foreach (var item in Model)
                {
                    @if (item.MadeBy == ViewBag.name && item.TransactionType=="Credit")
                    {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.TransactionId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MadeBy)
                    </td>
                    <td>
                        Rs. @Html.DisplayFor(modelItem => item.TransactionAmount)
                    </td>
                    <td class="bg-success">
                        @Html.DisplayFor(modelItem => item.TransactionType)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td class="bg-success">
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        Rs. @Html.DisplayFor(modelItem => item.Balance)
                    </td>
                </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>
<div id="showDebit" class="myDiv" style="display:none">
    <div class="col-md-12">
        <table class="table table-sm">
            <thead class="thead-dark">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.TransactionId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.MadeBy)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.MadeTo)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TransactionAmount)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TransactionType)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Date)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Status)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Balance)
                    </th>
                </tr>
            </thead>
            <tbody class="bg-light">
                @foreach (var item in Model)
                {
                    @if (item.MadeBy == ViewBag.name && item.TransactionType == "Debit")
                    {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.TransactionId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MadeBy)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MadeTo)
                    </td>
                    <td>
                        Rs. @Html.DisplayFor(modelItem => item.TransactionAmount)
                    </td>
                    <td class="bg-danger">
                        @Html.DisplayFor(modelItem => item.TransactionType)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td class="bg-danger">
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        Rs. @Html.DisplayFor(modelItem => item.Balance)
                    </td>
                </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>
<div class="text-center">
    <a href="@Url.Action("Def", "Home")">Back to Main Menu</a>
</div>