BankProject/Controllers/BankInformationController.cs
using BankProj.BankApplication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;

namespace BankProj.Controllers
{
    public class BankInformationController : Controller
    {
        private readonly AssignmentDBContext _context;
  
        public BankInformationController(AssignmentDBContext context)
        {
            _context = context;
        }
      
        // GET: UserAccountDetails
        public async Task<IActionResult> Index()
        {
            string data = HttpContext.User.Identity.Name;
            if (data == null)
            {
                return NotFound();
            }

            var userAccountDetail = await _context.UserAccountDetails
                .FirstOrDefaultAsync(m => m.Email == data);
            if (userAccountDetail == null)
            {
                return NotFound();
            }
            var bankinfo = await _context.BankInformations.FirstOrDefaultAsync(n => n.AccountNumber == userAccountDetail.AccountNumber);
            return View(bankinfo);
        }
        [HttpPost]
        public IActionResult Index(int creditamount)
        {
            string data = HttpContext.User.Identity.Name;
            var userAccountDetail =  _context.UserAccountDetails
                .FirstOrDefault(m => m.Email == data);
            return RedirectToAction("Transdetail","TransactionDetail",new {credit=creditamount,name=userAccountDetail.FullName,debit=0,toname=""});
        }
        public IActionResult Debit(string accno, string bankname, string ifsc, string receivername, int debitamount)
        {
            string data = HttpContext.User.Identity.Name;
            var userAccountDetail = _context.UserAccountDetails
                .FirstOrDefault(m => m.Email == data);
            return RedirectToAction("Transdetail", "TransactionDetail", new {credit = 0, name = userAccountDetail.FullName, debit = debitamount, toname = receivername });
        }
        
    }
}

BankProject/Controllers/HomeController.cs
using BankProj.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BankProj.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        [Authorize]
        public IActionResult Privacy()
        {
            return View();
        }
        [Authorize]
        public IActionResult Def()
        {
            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BankProject/Controllers/UserAccountDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BankProj.BankApplication;
using System.Security.Claims;

namespace BankProj.Controllers
{
    public class UserAccountDetailsController : Controller
    {
        private readonly AssignmentDBContext _context;

        public UserAccountDetailsController(AssignmentDBContext context)
        {
            _context = context;
        }

        // GET: UserAccountDetails
        public async Task<IActionResult> Index()
        {
            return View(await _context.UserAccountDetails.ToListAsync());
        }

        // GET: UserAccountDetails/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userAccountDetail = await _context.UserAccountDetails
                .FirstOrDefaultAsync(m => m.Email == id);
            if (userAccountDetail == null)
            {
                return NotFound();
            }

            return View(userAccountDetail);
        }

        // GET: UserAccountDetails/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: UserAccountDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FullName,DateofBirth,Email,Phone,City,State,AccountNumber")] UserAccountDetail userAccountDetail)
        {
            if (ModelState.IsValid)
            {
                _context.Add(userAccountDetail);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(userAccountDetail);
        }

        // GET: UserAccountDetails/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userAccountDetail = await _context.UserAccountDetails.FindAsync(id);
            if (userAccountDetail == null)
            {
                return NotFound();
            }
            return View(userAccountDetail);
        }

        // POST: UserAccountDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("FullName,DateofBirth,Email,Phone,City,State,AccountNumber")] UserAccountDetail userAccountDetail)
        {
            if (id != userAccountDetail.Email)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(userAccountDetail);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserAccountDetailExists(userAccountDetail.Email))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(userAccountDetail);
        }

        // GET: UserAccountDetails/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userAccountDetail = await _context.UserAccountDetails
                .FirstOrDefaultAsync(m => m.Email == id);
            if (userAccountDetail == null)
            {
                return NotFound();
            }

            return View(userAccountDetail);
        }

        // POST: UserAccountDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var userAccountDetail = await _context.UserAccountDetails.FindAsync(id);
            _context.UserAccountDetails.Remove(userAccountDetail);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
       
        private bool UserAccountDetailExists(string id)
        {
            return _context.UserAccountDetails.Any(e => e.Email == id);
        }
    }
}

BankProject/Views/Home/Def.cshtml
@{
    ViewData["Title"] = "Main Page";
    ViewBag.name = User.Identity.Name;
}
    <div class="row">
        <div class="col-3 text-white bg-warning">
            <ul id="ListBank" class="nav flex-column">
                <li class="nav-item">
                    <a class="nav-link active" href="@Url.Action("Index", "UserAccountDetails")">Account Details</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "BankInformation")">Make a New Payment</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "TransactionDetail")">Transaction Details</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("passbook", "TransactionDetail")">Print Passbook</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Creditcard" asp-area="Account">Credit Card Enquiry</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Loan" asp-area="Account">Loan</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Investment" asp-area="Account">Investment</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Profile" asp-area="Account">My Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="HelpDesk" asp-area="Account">HelpDesk</a>
                </li>
            </ul>
        </div>
       <div class="vr"></div>
        <div class="col-9 bg-light">
            <div class="container">
                <p class="lead text-justify">
                    Eurofins Bank Limited is an Indian banking and financial services company headquartered in Mumbai. It is India's largest private sector bank by assets and world's 10th largest bank by market capitalisation as of April 2021. It is the third largest company by market capitalisation of $122.50 billion on the Indian stock exchanges. It is also the fifteenth largest employer in India with nearly 120,000 employees. Eurofins Bank was incorporated in 1994 as a subsidiary of the Housing Development Finance Corporation, with its registered office in Mumbai, Maharashtra, India. Its first corporate office and a full-service branch at Sandoz House, Worli were inaugurated by the then Union Finance Minister, Manmohan Singh.
                    As of 30 June 2019, the bank's distribution network was at 5,500 branches across 2,764 cities. It has installed 430,000 POS terminals and issued 23,570,000 debit cards and 12 million credit cards in FY 2017. It has a base of 1,16,971 permanent employees as of 21 March 2020. In March 2020, Housing Development Finance Corporation, parent company of Eurofins Bank, made an investment of ₹1,000 crores in Yes Bank. As per the scheme of reconstruction of Yes Bank, 75% of the total investment by the corporation would be locked in for three years. On 14 March, Yes Bank allotted 100 crore shares of the face value of ₹2 each for consideration of ₹10 per share (including ₹8 premium) to the Corporation aggregating to 7.97 percent of the post issue equity share capital of Yes bank.
                </p>
            </div>
        </div>
    </div>

BankProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
    ViewBag.MetaRefresh = "<meta http-equiv='refresh' content='0;url=" + Url.Action("Def", "Home") + "' />";
}
else
{
<div class="row">
    <div class="col-md-6">
        <img src="~/Images/bank.png" height="450" width="450" alt="bank image" />
    </div>
    <div class="col-md-6 text-center">
        <div class="card text-white bg-warning" style="max-width: 40rem;">
            <div class="card-header">Login</div>
            <div class="card-body text-white">
                <h5 class="card-title">Existing user? Login..</h5>
                <p class="card-text">If you're a pre existing customer kindly login to proceed further</p>
                <a class="nav-link text-uppercase btn-info" asp-area="Identity" asp-page="/Account/Login">Login</a>
            </div>
        </div>
        <hr />
        <br />
        <div class="card text-white bg-info" style="max-width: 40rem;">
            <div class="card-header">Register</div>
            <div class="card-body text-white">
                <h5 class="card-title">Create a new user account</h5>
                <p class="card-text">Register to enjoy next-gen hassle free banking by a click</p>
                <a class="nav-link  btn-warning" asp-area="Identity" asp-page="/Account/Register">Register</a>
            </div>
        </div>
    </div>
</div>

}